// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3YYOs6XtG1CHETQpv_qzr1liPVHxCVwA',
    appId: '1:546500845819:web:a2539d3f2373b1998d905e',
    messagingSenderId: '546500845819',
    projectId: 'psm-app-661de',
    authDomain: 'psm-app-661de.firebaseapp.com',
    storageBucket: 'psm-app-661de.firebasestorage.app',
    measurementId: 'G-8EX4GMXQ1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfZZu_A1C_2x_g9mprx7MF33ti1Qti3nU',
    appId: '1:546500845819:android:9e67a062fe9e1c028d905e',
    messagingSenderId: '546500845819',
    projectId: 'psm-app-661de',
    storageBucket: 'psm-app-661de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnu-U4UCApJlqSDUpJRyxu4W6bxnyJnd0',
    appId: '1:546500845819:ios:31dedc036ade552e8d905e',
    messagingSenderId: '546500845819',
    projectId: 'psm-app-661de',
    storageBucket: 'psm-app-661de.firebasestorage.app',
    iosBundleId: 'com.example.psmMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnu-U4UCApJlqSDUpJRyxu4W6bxnyJnd0',
    appId: '1:546500845819:ios:31dedc036ade552e8d905e',
    messagingSenderId: '546500845819',
    projectId: 'psm-app-661de',
    storageBucket: 'psm-app-661de.firebasestorage.app',
    iosBundleId: 'com.example.psmMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3YYOs6XtG1CHETQpv_qzr1liPVHxCVwA',
    appId: '1:546500845819:web:cacb916e065fe2fc8d905e',
    messagingSenderId: '546500845819',
    projectId: 'psm-app-661de',
    authDomain: 'psm-app-661de.firebaseapp.com',
    storageBucket: 'psm-app-661de.firebasestorage.app',
    measurementId: 'G-EWJ1JXZQ78',
  );
}
